### ISSUE TITLE
A secure yet efficient way to access from child (Rec) to parent (Rd)

### ISSUE THREAD

**Issue by jinbpark** [islet-project/islet#222]
e.g., REC_ENTER
```
// grab the lock for Rec
let mut rec_granule = get_granule_if!(arg[0], GranuleState::Rec)?;
let mut rec = rec_granule.content_mut::<Rec>();

rec.rd.id();  // --> how to implement reading parents' variables in a secure manner? (Rd.id) 
rec.rd.ipa_bits();
```

- Rules that can apply to child-to-parent access
  - Rule-1: Child-Parent relationship has to be managed through reference-counting mechanisms. (we already doing it for Rec-Rd). This is because, at the moment of Child trying to access Parent, the Parent has to be guaranteed alive.
  - Rule-2: Child is allowed to access read-only variables that Parent has.
  - e.g., Rec (Child) is allowed to access read-only variables (realm_id, ipa_bits) that Rd (Parent) has.
    - This rule can apply to any situation in which a child-parent relationship plays. (one more example is: Rec (Parent) - RecAux (Child))
  - As long as this rule is followed, Child can access those variables without acquiring the lock of Parent.

- Main question:  how to design and implement a secure interface for the above child-to-parent access rules?
  - <TODO> there will be multiple ways to do it..

**Comment by nook1208** [comment]
When I searched, there is no way to define immutable field in struct.
I think that adding private `realm_id` and `ipa_bits` field in Rec and make only `init()` and getter function is the best like the following comment in [this reference](https://stackoverflow.com/questions/23743566/how-can-i-force-a-structs-field-to-always-be-immutable-in-rust/23748710#23748710)

> The best, as [Lily Ballard noted](https://stackoverflow.com/a/23748710/155423), is that you can declare your Shape field as private and make a getter method using impl A {...}.

let me make a PR for it :)

**Comment by jinbpark** [comment]
`Rec and making only init() and getter function` --> I agree this is good enough.

My initial thought on how to implement this is as follows.
```
// define accessor
impl<'a, E> EntryGuard<'a, E> {
    // new function for child-parent access
    // NOTE:  ==> add a comment here about the two rules for child-parent access
    pub fn parent_content<T: Content>(&self) -> &T {
       // E:  the type of child (e.g., Rec),   T: the type of parent (e.g., Rd)
       // <TODO>  do type checking--> it looks like, either (1) or (2). ==> this is for Rule-1.
       //     (1) if E::type == Rec && T::type == Rd,  error otherwise  
       //     (2) if E::type::get_parent_type() == T::type,  error otherwise
       unsafe { &*(self.addr as *const T) }
    }

   // do not make parent_content_mut() as it violates Rule-2.  ==> this is for Rule-2.
   // pub fn parent_content_mut<T: Content>(&mut self) -> &mut T {
}

// how to use it
let mut rec_granule = get_granule_if!(arg[0], GranuleState::Rec)?;
let mut rec = rec_granule.content_mut::<Rec>();
let rd = rec_granule.parent_content::<Rd>();  // accessing Rd (parent) still requires the lock of Rec (child) but not require the lock of Rd (parent).
...
rd.id();
rd.ipa_bits();
```

**Comment by nook1208** [comment]
I see. thank you for the code. if we have to read other fields of parent a lot besides `realm_id`, `ipa_bits`, then that's a good approach.
Please let me know if you are already implementing it :)

**Comment by jinbpark** [comment]
> Please let me know if you are already implementing it :) 

Nothing done yet. Appreciate it if you bring up this issue and make a draft PR! I'll happily get involved with that PR after that draft.
