### ISSUE TITLE
Rule checker workflow is failing on the main branch

### ISSUE THREAD

**Issue by zpzigi754** [islet-project/islet#260]
Currently, CI on the main branch does not pass all its checks, because rule checker workflow's actions-rs/audit-check@v1 is failing with the below error.
```
Error: Resource not accessible by integration
```

I've confirmed that the failure is caused by [the lacking permission](https://github.com/orgs/community/discussions/60820): only read permission is allowed for the workflow. However, I cannot select the option to give write permission in the `Settings->Actions->General->Workflow permissions` for some reasons.

**Comment by bitboom** [comment]
Thanks for checking this issue!.

I checked that needs the owner permission of our organization, not repositories.
I turn on the permission.

FYI, organization owner permission will be moved from me to `islet@samsung.com` which will be created newly.
