### ISSUE TITLE
Reproduce veraison demo

### ISSUE THREAD

**Issue by jinbpark** [islet-project/islet#278]
@p-sawicki2 ,

I'm trying to reproduce the result of the veraison example.
I faced the following error when doing `run.sh` in `veraison/provisioning`.
```
Provisioning generated Corim
+ /home/jinbum/ssd/github/islet/examples/veraison/services/deployments/docker/veraison -- cocli corim submit --corim-file=corim.cbor --api-server=http://provisioning-service:8888/endorsement-provisioning/v1/submit '--media-type='\''application/corim-unsigned+cbor; profile=http://arm.com/cca/ssd/1'\'''
Error: submit CoRIM payload failed reason: run failed: submit request failed: Post "http://provisioning-service:8888/endorsement-provisioning/v1/submit": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

Do you have any idea on this issue?

**Comment by p-sawicki2** [comment]
@L0czek Could you check that error?

**Comment by jinbpark** [comment]
Oh, I resolved it myself.  I guess it was a my local configuration error.  Closed this issue. (not yet successfully reproduced it as a whole though)

**Comment by jinbpark** [comment]
One more question--

I faced the following error message, when realm-application is executing `let conn = ClientConnection::new()` in client.rs.

```
# RUST_LOG=info ./bin/realm-application -r root-ca.crt -u 193.168.10.15:1337

[  161.752816] __vm_enough_memory: pid: 115, comm: realm-applicati, no enough memory for the allocation
[  161.772883] __vm_enough_memory: pid: 115, comm: realm-applicati, no enough memory for the allocation
[  161.793734] __vm_enough_memory: pid: 115, comm: realm-applicati, no enough memory for the allocation
memory allocation of 9903538456 bytes failed
Aborted
```

One change I made to realm-application is, I used a pre-made RsaPrivateKey instead of generating RsaPrivateKey (because it is too slow..).  I think this error has something to do with my change. (but when I tested the pre-made rsa key pair, it went successful in Realm)
Anyway, have you faced this kind of error before??

**Comment by p-sawicki2** [comment]
I wonder if it is not the same issue as #274
Could you check what happens if the executable is moved into the /root folder?

**Comment by jinbpark** [comment]
> I wonder if it is not the same issue 

It was the same issue. I've reproduced well the whole procedure specified in RUN.md. Thanks! (CLOSED this issue)

**Comment by darshanp4** [comment]
@jinbpark gentle remainder!

**Comment by zos** [comment]
There are currently some different issues with veraison in our demo. For the newest version of veraison I had to make some changes to examples/veraison/bootstrap.sh (services use https by default, policy scheme has changed name) and to veraison itself (I had some problems with go package caching and had to get pocli tool from specified commit). They are here: https://github.com/islet-project/islet/tree/dev/z.abramowska/veraison_bootstrap_fix . But I didn't fix problems with uploading endorsements etc (like the one with cocli).
