### ISSUE TITLE
How to get a CCA machine or simulate CCA chip on X86_64?

### ISSUE THREAD

**Issue by blossomin** [islet-project/islet#280]
Since I don't get a CCA chip now, how to simulate or buy one?

**Comment by bokdeuk-jeong** [comment]
Hi, you can download a simulator from Arm for free at https://developer.arm.com/Tools%20and%20Software/Fixed%20Virtual%20Platforms.
Or you can use a local copy of it in Islet. We are using Armv-A Base RevC AEM FVP.
