### ISSUE TITLE
RMM v1.0-eac5 support

### ISSUE THREAD

**Issue by bokdeuk-jeong** [islet-project/islet#291]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/BD1FD0~1.JEO/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/BD1FD0~1.JEO/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

  | ACS TEST SUIT | PASS/FAIL |  
-- | -- | -- | --
1 | cmd_rmi_version | O |  
2 | cmd_granule_delegate | O |  
3 | cmd_granule_undelegate | O |  
4 | cmd_realm_create | O |  
5 | cmd_rsi_version | O |  
6 | cmd_realm_activate | O |  
7 | cmd_rtt_read_entry | O |  
8 | cmd_rtt_init_ripas | O |  
9 | cmd_rtt_create | O |  
10 | cmd_data_create | O |  
11 | cmd_rtt_map_unprotected | O | 
12 | cmd_rec_create | O |  
13 | cmd_rec_enter | O |  
14 | cmd_multithread_realm_up | O |  
15 | cmd_multithread_realm_mp | O |   // not working, reinspection required
16 | cmd_rsi_features | O |  
17 | cmd_data_create_unknown | O |  
18 | cmd_secure_test | - |  
19 | cmd_realm_config | O |  
20 | cmd_ipa_state_get | O |  
21 | cmd_ipa_state_set | O |  
22 | cmd_psci_complete | O |  
23 | cmd_rmi_features | O |  
24 | cmd_rec_aux_count | O |  
25 | cmd_data_destroy | O |  
26 | cmd_realm_destroy | O |  
27 | cmd_rec_destroy | O |  
28 | cmd_rtt_destroy | O | // excluded RTT FOLD cases, test: RTTE_STATE_ASSIGNED
29 | cmd_rtt_unmap_unprotected | O |  
30 | cmd_psci_features | O |  
31 | cmd_psci_version | O |  
32 | cmd_cpu_off | O |  
33 | cmd_cpu_suspend | O |  
34 | cmd_system_off | O |  
35 | cmd_system_reset | O |  
36 | cmd_measurement_read | O |  
37 | cmd_measurement_extend | O |  
38 | cmd_attestation_token_init | O |  
39 | cmd_attestation_token_continue | O |  
40 | cmd_host_call | O |  
41 | cmd_affinity_info | O |  
42 | cmd_cpu_on | O |  
43 | cmd_rtt_set_ripas | O | 
44 | cmd_rtt_fold |   |  // not supporting it yet

 /*ATTESTATION and MEASUREMENT testcase*/
  | ACS TEST SUIT | PASS/FAIL |  
-- | -- | -- | --
1 | measurement_immutable_rim |   |  
2 | measurement_initial_rem_is_zero |   |  
3 | measurement_rim_order |   |  
4 | attestation_token_verify |   |  
5 | attestation_rpv_value |   |  
6 | attestation_challenge_data_verification |   |  
7 | attestation_token_init |   |  
8 | attestation_realm_measurement_type |   |  
9 | attestation_platform_challenge_size |   |  
10 | attestation_rem_extend_check |   |  
11 | attestation_rem_extend_check_realm_token |   |  
12 | attestation_rec_exit_irq |   |  

/*memory management testcase */
  | ACS TEST SUIT | PASS/FAIL |  
-- | -- | -- | --
1 | mm_ripas_change | O |  
2 | mm_ripas_change_reject | O |  
3 | mm_ripas_change_partial | O |  
4 | mm_hipas_assigned_ripas_empty_da_ia | X |  TODO: SEA injection to Realm required
5 | mm_hipas_unassigned_ns_da_ia | O |  
6 | mm_unprotected_ipa_boundary | O |  
7 | mm_protected_ipa_boundary | O |  
8 | mm_gpf_exception | O |  
9 | mm_rtt_translation_table | O |  
10 | mm_rtt_fold_assigned |   |  TODO
11 | mm_rtt_fold_unassigned |   |  TODO
12 | mm_rtt_fold_unassigned_ns |   |  TODO
13 | mm_rtt_fold_assigned_ns |   |  TODO
14 | mm_ripas_destroyed_da_ia |   |  TODO
15 | mm_hipas_unassigned_ripas_empty_da_ia | X |   TODO: SEA injection to Realm required
16 | mm_hipas_unassigned_ripas_ram_da_ia | O |  
17 | mm_feat_s2fwb_check_1 | O |  
18 | mm_rtt_level_start | O |  
19 | mm_feat_s2fwb_check_2 | O |  
20 | mm_feat_s2fwb_check_3 | O |  
21 | mm_ha_hd_access | O |  
22 | mm_realm_access_outside_ipa | O |  

 /*Exception model*/
  | ACS TEST SUIT | PASS/FAIL |  
-- | -- | -- | --
1 | exception_rec_exit_wfe | -  |  Skipped by ACS-test
2 | exception_rec_exit_wfi |  O |  
3 | exception_rec_exit_irq |  O |  
4 | exception_rec_exit_fiq |   |  
5 | exception_rec_exit_hostcall | O  |  
6 | exception_rec_exit_psci | O  |  
7 | exception_realm_unsupported_smc | O  |  
8 | exception_rec_exit_hvc | O  |  
9 | exception_rec_exit_ripas | O  |  
10 | exception_rec_exit_ia | O  |  
11 | exception_emulatable_da | O  |  
12 | exception_non_emulatable_da | O  |  
13 | exception_non_emulatable_da_1 | O  |  
14 | exception_non_emulatable_da_2 | O  |  

 /*GIC testcase*/
  | ACS TEST SUIT | PASS/FAIL |  
-- | -- | -- | --
1 | gic_hcr_invalid | O  |  
2 | gic_ctrl_list_invalid | O  |  
3 | gic_ctrl_list | O  |  
4 | gic_obsv_vmcr | O  |  
5 | gic_timer_val_read | O  |  
6 | gic_timer_rel1_trig | O  |  
7 | gic_timer_nsel2_trig | O  |  
8 | gic_ctrl_hcr | O  |  

 /*PMU and DEBUG testcase*/
  | ACS TEST SUIT | PASS/FAIL |  
-- | -- | -- | --
1 | pmu_overflow | -  |   Skipped by ACS-test and not supported by Iset RMM

</body>

</html>

**Comment by p-sawicki2** [comment]
As to  /ATTESTATION and MEASUREMENT testcase/ these tests are covered by #342.
