### ISSUE TITLE
SDK should point to rust_rsi instead of rsi_el0

### ISSUE THREAD

**Issue by jinbpark** [islet-project/islet#382]
It seems that rsi_el0 is deprecated and [rust-rsi](https://github.com/islet-project/remote-attestation/tree/main/lib/rust-rsi) in remote-attestation repo has replaced rsi-el0.
rsictl, a tool to test attest and verify, points to rust-rsi and thus works well, while islet-cli pointing to rsi-el0 doesn't work out (error log: Failed to get attestation report).

This is because, 
sdk is using `rsi_el0::attestation_token(&challenge)` which is incompatible with the current rsi.ko.
SDK should be updated like `rust_rsi::attestation_token(&challenge)` as in rsictl.

**Comment by bitboom** [comment]
Both the islet-sdk and islet-cli code are still using the old `rsi_el0` as you said. Additionally, the islet-cli duplicates functionality with `rsictl`. (This divergence occured to meet the Certifier's requirements for the demo purpose during the CC Summit. The requirement was that the simulated version must work within x86.)

IMHO, it would be better to deprecated the CLI, and if the requirement is still valid, incorporate it into `rsictl` instead.

**Comment by bokdeuk-jeong** [comment]
@L0czek 
Could you also update ${islet}/realm/linux-rsi and point it to the eac5 version?

**Comment by bitboom** [comment]
It would be better to deprecate `islet-cli` and use `rsictl` as is. I will also update the `SDK` to point the latest remote attestation and clean up the diverged code.

**Comment by L0czek** [comment]
@bokdeuk-jeong 
> Could you also update ${islet}/realm/linux-rsi and point it to the eac5 version?

https://github.com/islet-project/islet/pull/367 already does that.

**Comment by p-sawicki2** [comment]
Hi @bitboom. Could you let us know when you are going to start working on the replacement of `islet-cli` with `rsictl`?
I'm asking, because we're currently involved in the refactoring task (#388), and having that information would help us with planning our work.

**Comment by bitboom** [comment]
> Hi @bitboom. Could you let us know when you are going to start working on the replacement of `islet-cli` with `rsictl`? I'm asking, because we're currently involved in the refactoring task (#388), and having that information would help us with planning our work.

I will start working on it this week. :)

**Comment by bitboom** [comment]
@p-sawicki2 This issue is resolved :)
